app.controller('MainController', ['$scope', function($scope){
	$scope.testimonials = ["This is the first example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH", "This is the second example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH", "This is the third example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH", "This is the fourth example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH", "This is the fifth example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH", "This is the sixth example of a McWee Review!!!! It is a very good example. This is some more text for the example. -COMPANY MCWEE WORKED WITH"];

	$scope.works = [
		{name:"First Work Example", description: "First Piece of Work"},
		{name:"Second Work Example", description: "Second Piece of Work"},
		{name:"Third Work Example", description: "Third Piece of Work"},
		{name:"Fourth Work Example", description: "Fourth Piece of Work"},
		{name:"Fifth Work Example", description: "Fifth Piece of Work"},
		{name:"Sixth Work Example", description: "Sixth Piece of Work"}
	];

	$scope.aboutMe = {
		short : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras at imperdiet turpis, eu vehicula ipsum. Proin in aliquam velit. Sed et rutrum urna. Integer venenatis vitae ligula eget luctus. Morbi sed lacus eu mauris aliquam congue non nec elit. Aenean et lectus a mauris condimentum gravida. Nullam ac velit eu est lacinia fermentum ullamcorper scelerisque tortor. Phasellus efficitur eleifend metus non dictum. Phasellus vitae metus ipsum. Pellentesque porta, ex nec elementum volutpat, eros lacus auctor ante, et placerat ex purus id tortor. Duis in molestie nulla, non condimentum lectus.",
		long : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras at imperdiet turpis, eu vehicula ipsum. Proin in aliquam velit. Sed et rutrum urna. Integer venenatis vitae ligula eget luctus. Morbi sed lacus eu mauris aliquam congue non nec elit. Aenean et lectus a mauris condimentum gravida. Nullam ac velit eu est lacinia fermentum ullamcorper scelerisque tortor. Phasellus efficitur eleifend metus non dictum. Phasellus vitae metus ipsum. Pellentesque porta, ex nec elementum volutpat, eros lacus auctor ante, et placerat ex purus id tortor. Duis in molestie nulla, non condimentum lectus. Curabitur vitae aliquam felis. Nunc vel posuere mi. Phasellus condimentum tellus eu nisi cursus dapibus. Nunc sed sodales ex. Donec arcu lacus, pellentesque ac justo vitae, malesuada maximus justo. Vivamus consequat pellentesque mauris, ut tempus neque accumsan porta. Proin condimentum libero a augue sodales placerat. Maecenas elit dui, ultricies ut efficitur vel, mattis dignissim mauris. Pellentesque dui enim, eleifend et tempor non, ultrices non neque. Aliquam vitae viverra lorem, vel tristique enim. Curabitur vitae magna a purus lacinia feugiat id vel libero. Aenean iaculis arcu sit amet mi maximus, sit amet congue eros laoreet. Ut cursus orci neque, pretium placerat justo semper at. Sed luctus arcu at enim rutrum, ac tincidunt risus ultricies. Etiam id sodales tellus. Nunc ac lobortis ligula. Morbi pellentesque ultricies massa ac finibus. Phasellus varius augue nulla, nec lobortis lacus dapibus a. Sed sit amet mi nulla. In auctor ante vitae justo consectetur, dapibus interdum ex faucibus. Suspendisse potenti. Etiam ultrices arcu aliquet est imperdiet sollicitudin. Praesent volutpat nisi ligula, quis egestas ante ullamcorper nec. Mauris nisi tellus, gravida vitae luctus at, ullamcorper quis velit. Sed pulvinar odio et est suscipit, nec iaculis dui pulvinar. Morbi vitae vehicula ante. Duis sed massa sodales, dictum nibh sit amet, ultrices nunc. Maecenas non urna lorem. Ut tellus ligula, semper sit amet semper sit amet, accumsan a dui. Vestibulum in ullamcorper lacus. Pellentesque non viverra mauris. Aenean lobortis finibus quam nec accumsan. Praesent mollis dolor nec risus sagittis, a aliquet neque vulputate. Nulla feugiat, diam eu dignissim elementum, diam augue pulvinar tortor, et consequat ipsum dui ut lacus. Phasellus a sodales enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent id leo ut libero ultrices vehicula dictum vitae dui. Aliquam ac tortor tempor, rutrum ipsum quis, vestibulum tellus. Nam turpis libero, blandit a sagittis eu, gravida rutrum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et auctor nisl. Integer auctor nulla at velit imperdiet bibendum."
	};


}]);